///////////////////////////////////////////////////////////
//  TaskPool.cs
//  Implementation of the Class TaskPool
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7tti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace Multithreading
{
	public class ArchiverTaskPool
    {
        public Mutex mutex = new Mutex();

        Queue<ITaskInfo> _tasksInfo;

        public bool IsHasTasks()
        {
            return _tasksInfo.Count > 0;
        }

        public int TaskCount()
        {
            return _tasksInfo.Count;
        }

        public bool isActive()
        {
            return true;
        }

        public ArchiverTaskPool()
        {
            _tasksInfo = new Queue<ITaskInfo>();
        }

        public void AddTask(ITaskInfo task)
        {
            mutex.WaitOne();
            _tasksInfo.Enqueue(task);
            mutex.ReleaseMutex();
        }

        public ITaskInfo NextTask()
        {
            mutex.WaitOne();
            ITaskInfo task = null;
            if (IsHasTasks())
            {
                task = _tasksInfo.Dequeue();
            }
            mutex.ReleaseMutex();
            return task;
        }
	}
}