///////////////////////////////////////////////////////////
//  Compressor.cs
//  Implementation of the Class Compressor
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:22
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;
using System.IO;
using System.Threading;

namespace Multithreading
{
    /// <summary>
    /// Класс сжатия
    /// </summary>
    public class Compressor
    {
        /// <summary> 
        /// 
        /// </summary>
        private QueueTaskPool _readTaskPool;
        private QueueTaskPool _compressTaskPool;
        private HashtableTaskPool _writeTaskPool;
        /// <summary> 
        /// Флаг для потоков, сигнализирующий, что процесс генерации задач не окончен
        /// </summary>
        private bool _await = false;
        /// <summary> 
        /// Счётчик блоков для наблюдателя
        /// </summary>
        private Int64 _lastBlock;
        /// <summary> 
        /// Длина исходного файла
        /// </summary>
        private Int64 _fileLength;
        /// <summary> 
        /// Количество кусков
        /// </summary>
        private Int64 _batchCount;
        /// <summary> 
        /// Длина каждого куска
        /// </summary>
        private Int64 _readBlockSize;
        /// <summary> 
        /// Длина последнего куска
        /// </summary>
        private Int64 _lastPiece;

        /// <summary> 
        /// Фабрика для создания задач
        /// </summary>
        private ITaskFactory _taskFactory;
        /// <summary> 
        /// Количество доступных ядер
        /// </summary>
        private int _cores;
        /// <summary> 
        /// Максимальное число задач
        /// </summary>
        private int _maxTasks;

        /// <summary>
        /// Конструктор класса сжатия
        /// </summary>
        /// <param name="factory">
        /// Фабрика для создания задач
        /// </param>
        /// <param name="readBlockSize">
        /// Размер блока для чтения и сжатия
        /// </param>
        /// <param name="cores">
        /// Количество доступных потоков для сжатия
        /// </param>
        /// <param name="maxTasks">
        /// Ограничение по количеству задач, чтобы избежать переполнения памяти
        /// </param>
        public Compressor(ITaskFactory factory, Int64 readBlockSize = 4096, int cores = 2, int maxTasks = 100)
        {
            _taskFactory = factory;
            _readBlockSize = readBlockSize;
            _cores = cores;
            _maxTasks = maxTasks;
        }

        /// <summary>
        /// Запустить сжатие заданного файла и сохранить по указанному пути
        /// </summary>
        /// <param name="readFile">
        /// Дескриптор файла для чтения
        /// </param>
        /// <param name="writeFile">
        /// Дескриптор файла для записи
        /// </param>
        public bool ProcessFile(FileDescriptor readFile, FileDescriptor writeFile)
        {
            _readTaskPool = new QueueTaskPool();
            _compressTaskPool = new QueueTaskPool();
            _writeTaskPool = new HashtableTaskPool();

            // Создание задач чтения файла
            _fileLength = readFile.GetDescription.Length;
            _batchCount = _fileLength / _readBlockSize;
            _lastPiece = _fileLength % _readBlockSize;

            try
            {
                _await = true;

                // Запуск потока чтения
                {
                    new Thread(ReadingThread).Start(readFile);
                }
                // Запустить потоки распаковки
                for (int i = 0; i < _cores; i++)
                {
                    new Thread(CompressingThread).Start();
                }
                // Запустить поток записи
                {
                    new Thread(WritingThread).Start(writeFile);
                }
                // Запуск потока генерации задач
                {
                    new Thread(GeneratorThread).Start();
                }
            }
            catch (Exception exc)
            {
                Console.WriteLine("Can't process threads");
#if DEBUG
                Console.WriteLine(exc);
#endif
                return false;
            }

            // Наблюдатель - ждёт, пока не завершится последний кусок и обновляет прогресс
            while (_lastBlock < _batchCount)
            {
                Console.Clear();
                // Здесь должно высылаться оповещение контроллеру, чтобы тот обновил на GUI прогресс бар (W.I.P.) =]
                Console.WriteLine("Progress: {0}%", Math.Truncate(_lastBlock / (double)_batchCount * 100));
                Thread.Sleep(500);
            }
            if (_lastPiece > 0)
            {
                Thread.Sleep(100);
            }

            _await = false;
            return true;
        }

        /// <summary>
        /// Метод для потока генерации задач для чтения. Необходим для более гибкого распределения нагрузки на поток чтения файла
        /// </summary>
        private void GeneratorThread()
        {
            try
            {
                int wait = Convert.ToInt32(Math.Pow(_cores, 1.5));
                for (int i = 0; i < _batchCount; i++)
                {
                    // Защита от переполнения памяти
                    // Без этого произойдёт переполнение
                    // Нагенерируется больше задач, чем возможно обработать за промежуток времени, проверено на SSD
                    // TODO: Возможно подобрать более оптимальные значения maxTasks за счёт градиентного спуска
                    if (_readTaskPool.TaskCount() > _maxTasks)
                    {
                        --i;
                        continue;
                    }
                    _readTaskPool.AddTask(_taskFactory.CreateReadTask(i, _readBlockSize));
                }
                // Обработка последнего куска
                if (_lastPiece > 0)
                {
                    _readTaskPool.AddTask(_taskFactory.CreateReadTask(_batchCount, _lastPiece));
                }
            }
            catch(Exception exc)
            {
                Console.WriteLine("Error on generating reading tasks");
#if DEBUG
                Console.WriteLine(exc);
#endif
            }
        }

        /// <summary>
        /// Метод для потока чтения. Чтение и генерация задач сжатия происходит в 1 поток, что даёт максимальную нагрузку на диск
        /// </summary>
        /// <param name="obj">
        /// Дескриптор файла для записи
        /// </param>
        private void ReadingThread(object obj)
        {
            FileDescriptor read_file = obj as FileDescriptor;
            try
            {
                using (FileStream _fileToBeCompressed = read_file.GetDescription.OpenRead())
                {
                    Int64 lastBlock = 0;
                    while (_await)
                    {
                        // Защита от переполнения памяти
                        if (_compressTaskPool.TaskCount() > _maxTasks * _cores)
                        {
                            continue;
                        }
                        ITaskInfo taskInfo = null;
                        taskInfo = _readTaskPool.NextTask();
                        if (taskInfo == null)
                        {
                            continue;
                        }
                        _compressTaskPool.AddTask(_taskFactory.CreateProcessTask(lastBlock++, (taskInfo.Execute(_fileToBeCompressed) as byte[])));
                    }
                }
            }
            catch (Exception exc)
            {
                Console.WriteLine("Error on file reading");
#if DEBUG
                Console.WriteLine(exc);
#endif
                _await = false;
            }
        }

        /// <summary>
        /// Сжатие и генерация задач записи работает в том количестве потоков, сколько процессоров доступно системе, 
        /// давая распределённую и почти 100% нагрузку на все ядра процессора
        /// </summary>
        private void CompressingThread()
        {
            try
            {
                while (_await)
                {
                    // Защита от переполнения памяти
                    if (_writeTaskPool.TaskCount() > _maxTasks)
                    {                        
                        continue;
                    }
                    ITaskInfo taskInfo = _compressTaskPool.NextTask();
                    if (taskInfo == null)
                    {
                        continue;
                    }
                    _writeTaskPool.AddTask(_taskFactory.CreateWriteTask(taskInfo.GetId(), (taskInfo.Execute(null) as MemoryStream).ToArray()));
                }
            }
            catch (Exception exc)
            {
                Console.WriteLine("Error on file compressing");
#if DEBUG
                Console.WriteLine(exc);
#endif
                _await = false;
            }
        }

        /// <summary>
        ///  Запись происходит в один поток, так как требуется упорядочить сжатые блоки по Id через Hashtable
        /// </summary>
        private void WritingThread(object obj)
        {
            FileDescriptor writeFileDescriptor = obj as FileDescriptor;
            try
            {
                using (FileStream writeFileStream = writeFileDescriptor.GetDescription.OpenWrite())
                {
                    _lastBlock = 0;
                    while (_await)
                    {
                        ITaskInfo taskInfo = _writeTaskPool.NextTask() as ITaskInfo;
                        if (taskInfo == null)
                        {
                            continue;
                        }
                        taskInfo.Execute(writeFileStream);
                        _lastBlock++;
                    }
                }
            }
            catch (Exception exc)
            {
                Console.WriteLine("Error on file writing");
#if DEBUG
                Console.WriteLine(exc);
#endif
                _await = false;
            }
        }
    }
}