///////////////////////////////////////////////////////////
//  CompressionTask.cs
//  Implementation of the Class CompressionTask
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:22
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.IO.Compression;

namespace Multithreading
{
    /// <summary>
    /// Класс описания задачи сжатия
    /// </summary>
	public class CompressionTaskInfo : ITaskInfo
    {
        private Int64 _id;
        private byte[] _bytes;

		public CompressionTaskInfo(Int64 id, byte[] bytes)
        { 
            _id = id;
            _bytes = bytes;
		}

        public void Execute(object obj)
        {
            using (GZipStream compressStream = new GZipStream((MemoryStream)obj, CompressionLevel.Optimal))
            {
                compressStream.Write(_bytes, 0, _bytes.Length);
            }
        }

        public object GetData()
        {
            return _bytes;
        }

        public Int64 GetId()
        {
            return _id;
        }
    }
}