///////////////////////////////////////////////////////////
//  FileDescriptor.cs
//  Implementation of the Class FileDescriptor
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.IO.Compression;

namespace Multithreading {
	public class FileDescriptor {
		private FileInfo _file;

        public FileInfo GetDescription { get => _file; }

		~FileDescriptor(){

		}

        public FileDescriptor(string file_name)
        {
            _file = new FileInfo(file_name);
        }
	}
}