///////////////////////////////////////////////////////////
//  ITaskInfo.cs
//  Implementation of the Interface ITaskInfo
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Multithreading
{
    public interface ITaskInfo
    {
        /// <summary>
        /// Получение идентификатора задачи
        /// </summary>
        /// <returns>
        /// Long int
        /// </returns>
        Int64 GetId();
        /// <summary>
        /// Выполнение действий над данными. Необходимо для инкапсуляции куска данных
        /// </summary>
        /// <param name="obj">
        /// Обхект состояния для задачи
        /// </param>
        /// <returns>
        /// Данные, хранящиеся в описании задачи. В том случае, 
        /// если требуется получить данные
        /// </returns>
        object GetData();

        /// <summary>
        /// Выполнение действий над данными. Необходимо для инкапсуляции данных задачи, 
        /// чтобы использовать меньше памяти
        /// </summary>
        /// <param name="obj">
        /// Обхект состояния для задачи
        /// </param>
        void Execute(object obj);
    }
}
