///////////////////////////////////////////////////////////
//  IDecompressionTaskFactory.cs
//  Implementation of the Interface IDecompressionTaskFactory
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:19:29
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Multithreading
{
    public interface IUnzipperTaskFactory : ITaskFactory
    {
        ITaskInfo CreateDecompressionTask(Int64 id, byte[] bytes);
        ITaskInfo CreateDecompressionWriteTask(Int64 id, byte[] bytes);
    }
}