///////////////////////////////////////////////////////////
//  Program.cs
//  Implementation of the Class Program
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;
using System.IO;

using MultithreadingArchiver;

class Program
{
    /// <summary>
    /// Контейнер приложения
    /// </summary>
    /// <param name="args">
    /// Первый параметр - режим работы архиватора:
    /// c или compress - сжатие /
    /// d или decompress - деархивация;
    /// Второй параметр - исходный файл;
    /// Третий параметр - конечный файл
    /// </param>
    static void Main(string[] args)
    {
#if !DEBUG
        string mode = "decompress";
        string open_path = @"C:\Users\A7tti\source\repos\MultithreadingArchiver\Multithreading\bin\Release\film.mkv.gz";
        string save_path = @"C:\Users\A7tti\source\repos\MultithreadingArchiver\Multithreading\bin\Release\";
#else
        string mode = args[0];
        string open_path = args[1];
        string save_path = args[2];

        if (args.Length < 2)
        {
            throw new Exception("Unable command line arguments");
        }
#endif
        // Инициализация
        if (mode == "c" || mode == "compress")
        {
            Archiver.Compress(open_path, save_path);
        }
        else if (mode == "d" || mode == "decompress")
        {
            Archiver.Decompress(open_path, save_path);
        }
        // Ручной выход из программы, если перехвачен ctrl+c
        Environment.Exit(0);
    }
}