///////////////////////////////////////////////////////////
//  TaskFactory.cs
//  Implementation of the Class TaskFactory
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Multithreading
{
	public class UnzipperTaskFactory : ITaskFactory{

        public ITaskInfo CreateReadTask(Int64 id, Int64 length)
        {
            return new DecompressionReadTaskInfo(id, length);
        }

        public ITaskInfo CreateProcessTask(Int64 id, byte[] bytes)
        {
            return new DecompressionTaskInfo(id, bytes);
        }

        public ITaskInfo CreateWriteTask(Int64 id, byte[] bytes)
        {
            return new DecompressionWriteTaskInfo(id, bytes);
        }
    }
}