///////////////////////////////////////////////////////////
//  TaskFactory.cs
//  Implementation of the Class TaskFactory
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;

namespace MultithreadingArchiver
{
    /// <summary>
    /// Класс описания фабрики для задач сжатия
    /// </summary>
	class CompressionTaskFactory : ITaskFactory {
        public ITaskInfo CreateReadTaskInfo(Int64 id, Int64 length)
        {
            return new CompressionReadTaskInfo(id, length);
        }

        public ITaskInfo CreateProcessTaskInfo(Int64 id, byte[] bytes)
        {
            return new CompressionProcessTaskInfo(id, bytes);
		}

        public ITaskInfo CreateWriteTaskInfo(Int64 id, byte[] bytes)
        {
            return new CompressionWriteTaskInfo(id, bytes);
        }
    }
}