///////////////////////////////////////////////////////////
//  DecompressorTaskFactory.cs
//  Implementation of the Class DecompressorTaskFactory
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;

namespace MultithreadingArchiver
{
    /// <summary>
    /// Класс описания фабрики для задач распаковки
    /// </summary>
	class DecompressorTaskFactory : ITaskFactory{
        public ITaskInfo CreateReadTaskInfo(Int64 id, Int64 length)
        {
            return new DecompressionReadTaskInfo(id, length);
        }

        public ITaskInfo CreateProcessTaskInfo(Int64 id, byte[] bytes)
        {
            return new DecompressionProcessTaskInfo(id, bytes);
        }

        public ITaskInfo CreateWriteTaskInfo(Int64 id, byte[] bytes)
        {
            return new DecompressionWriteTaskInfo(id, bytes);
        }
    }
}