///////////////////////////////////////////////////////////
//  DecompressionProcessTaskInfo.cs
//  Implementation of the Class DecompressionProcessTaskInfo
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;
using System.IO;
using System.Linq;
using System.IO.Compression;

namespace MultithreadingArchiver
{
    /// <summary>
    /// Класс описания задачи распаковки
    /// </summary>
    class DecompressionProcessTaskInfo : ITaskInfo
    {
        private Int64 _id;
        private byte[] _bytes;

        public DecompressionProcessTaskInfo(Int64 id, byte[] bytes)
        {
            _id = id;
            _bytes = bytes;
        }

        /// <summary>
        /// Выполнение действий над данными. Необходимо для инкапсуляции данных задачи, 
        /// чтобы использовать меньше памяти
        /// </summary>
        /// <param name="obj">
        /// Обхект состояния для задачи
        /// </param>
        public object Execute(object obj)
        {
            using (MemoryStream memoryStream = new MemoryStream(_bytes))
            {
                using (GZipStream compressStream = new GZipStream(memoryStream, CompressionMode.Decompress))
                {
                    int size = BitConverter.ToInt32(_bytes, _bytes.Length - 4);
                    byte[] bytes = new byte[size];
                    compressStream.Read(bytes, 0, bytes.Length);
                    byte[] array = bytes.ToArray();
                    return array;
                }
            }
        }

        public object GetData()
        {
            return _bytes;
        }

        public Int64 GetId()
        {
            return _id;
        }
    }
}