///////////////////////////////////////////////////////////
//  IArchiverTaskPool.cs
//  Implementation of the Interface IArchiverTaskPool
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

namespace MultithreadingArchiver
{
    /// <summary>
    /// Интерфейс для инкапсуляции списка задач
    /// </summary>
    internal interface IArchiverTaskPool
    {
        int TaskCount();
        void AddTask(ITaskInfo task);
        ITaskInfo NextTask();
    }
}
