///////////////////////////////////////////////////////////
//  Program.cs
//  Implementation of the Class Program
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System;

using MultithreadingArchiver;

class Program
{
    /// <summary>
    /// Контейнер приложения
    /// </summary>
    /// <param name="args">
    /// Первый параметр - режим работы архиватора:
    /// c или compress - сжатие /
    /// d или decompress - деархивация;
    /// Второй параметр - исходный файл;
    /// Третий параметр - конечный файл
    /// </param>
    static void Main(string[] args)
    {
#if DEBUG
        string mode = "compress";
        string open_path = @"C:\Users\A7tti\source\repos\MultithreadingArchiver\MultithreadingArchiver\bin\Release\text.txt";
        string save_path = @"C:\Users\A7tti\source\repos\MultithreadingArchiver\MultithreadingArchiver\bin\Release\";
#else
        if (args.Length < 3)
        {
            Console.WriteLine("To compress or decompress please enter args:\n[compress | decompress] [source file path] [destination directory path]");
            return;
        }

        string mode = args[0];
        string open_path = args[1];
        string save_path = args[2];

#endif
        // Инициализация
        if (mode == "c" || mode == "compress")
        {
            Archiver.Compress(open_path, save_path);
        }
        else if (mode == "d" || mode == "decompress")
        {
            Archiver.Decompress(open_path, save_path);
        }
        else
        {
            Console.WriteLine("[compress | decompress]");
        }
        // Мануальный выход из программы, если перехвачен ctrl+c
        Environment.Exit(0);
    }
}