///////////////////////////////////////////////////////////
//  FileDescriptor.cs
//  Implementation of the Class FileDescriptor
//  Generated by Enterprise Architect
//  Created on:      15-апр-2019 23:18:23
//  Original author: A7ttim
///////////////////////////////////////////////////////////

using System.IO;

namespace MultithreadingArchiver
{
    /// <summary>
    /// Класс-контейнер для описания файла
    /// </summary>
	class FileDescriptor {
		private FileInfo _file;

        public FileInfo GetDescription { get => _file; }

        public FileDescriptor(string file_name)
        {
            _file = new FileInfo(file_name);
        }
	}
}